### ISSUE TITLE
Undefined method `each' for nil:NilClas

### ISSUE THREAD

**Issue by jhrocha** [JanGorman/uppercrust#2]
Hi! 
Your project is awesome. 
I'm having problems when trying to create the file. 

/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/parser.rb:115:in `extract_properties': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/parser.rb:12:in `initialize'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/generator.rb:35:in `new'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/generator.rb:35:in `block in read_files'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/generator.rb:33:in `each'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/generator.rb:33:in `read_files'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/generator.rb:15:in `generate'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/lib/uppercrust/cli.rb:10:in `generate'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/gems/uppercrust-0.0.1/bin/uppercrust:3:in `<top (required)>'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/bin/uppercrust:23:in `load'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/bin/uppercrust:23:in `<main>'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jhrochasousa/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

What could be ?

Thank you, again.

**Comment by JanGorman** [comment]
Hey, thanks for the report. I don't have time to check it out right now unfortunately but will do so over the weekend.

**Comment by JanGorman** [comment]
@jhrocha Is it possible for you to share the input files you're using?

**Comment by engineeringman** [comment]
Here's a very basic class I attempted to run on, which returned the same error:

```
{
  "AccountHolderName": "sample string 1",
  "AccountNumber": "sample string 2",
  "AccountType": 1,
  "DayOfMonth": 3,
  "MOPSequence": 4,
  "PaymentType": 0,
  "RoutingCode": "sample string 5"
}
```

I can't seem to get ANY files working

**Comment by JanGorman** [comment]
@engineeringman Thanks. On vacation right now, I can take a closer look next week but just briefly looking at the example you posted, that looks like a data json file, not schema. uppercrust solely exists to create [Mantle](https://github.com/Mantle/Mantle) compatible Objective-C files. The [JSON Schema](http://json-schema.org/examples.html) website lists some examples as does the uppercrust readme file of what is valid input.
